/* 诊断原因码与任务/单元错误码统一在这里中文化；
   未收录的新码原样展示，保留排查线索。 */
const processingCodeLabels: Record<string, string> = {
  OCR_RUNTIME_UNAVAILABLE: "OCR 服务不可用",
  OCR_FAILED: "OCR 识别失败",
  OCR_EMPTY: "OCR 未识别到文字",
  OCR_LOW_QUALITY: "OCR 质量偏低",
  AI_CALL_FAILED: "AI 调用失败",
  AI_INVALID_OUTPUT: "AI 输出格式异常",
  AI_TRUNCATED_OUTPUT: "AI 输出被截断",
  AI_PARTIAL_RESULT: "部分结果被证据校验拒绝",
  SUPPLEMENT_REQUIRED: "已追加遗漏补提取",
  SUPPLEMENT_UNRESOLVED: "补提取后仍有未核对项",
  POSTPROCESS_REDUNDANT: "重复结果已剔除",
  POSTPROCESS_IGNORED: "无效结果已忽略",
  POSTPROCESS_UNVERIFIED: "未验证结果已拦截",
  AI_UNMATCHED_CANDIDATES: "候选未全部核对",
  LEASE_EXPIRED: "任务执行超时",
  AI_ERROR: "AI 调用错误",
  AI_EMPTY_RESPONSE: "AI 无响应内容",
  AI_EMPTY_RESULT: "AI 未产出结果",
  AI_INVALID_JSON: "AI 输出格式异常",
  AI_NOT_CONFIGURED: "AI 服务未配置",
  AI_OUTPUT_TRUNCATED: "AI 输出被截断",
  AI_TASK_CANCELLED: "任务已取消",
  AI_TASK_NOT_IMPLEMENTED: "任务类型不支持",
  EMPTY_REPORT_PAGES: "报告无可用页面",
  EMPTY_REPORT_TEXT: "报告无可用文字",
  INVALID_PDF_PAGE_COUNT: "PDF 页数异常",
  INVALID_STORAGE_PATH: "存储路径异常",
  OCR_PAGE_SET_INCOMPLETE: "OCR 页面不完整",
  MINERU_AUTH_FAILED: "MinerU 认证失败",
  MINERU_RATE_LIMITED: "MinerU 请求受限",
  MINERU_TIMEOUT: "MinerU 解析超时",
  MINERU_NETWORK_ERROR: "无法连接 MinerU",
  MINERU_SERVICE_ERROR: "MinerU 服务不可用",
  MINERU_UPSTREAM_ERROR: "MinerU 拒绝请求",
  MINERU_UPSTREAM_FAILED: "MinerU 解析失败",
  MINERU_LIMIT_EXCEEDED: "超过 MinerU 官方限额",
  MINERU_INVALID_RESULT: "MinerU 结果损坏",
  MINERU_RESPONSE_LIMIT_EXCEEDED: "MinerU 结果超过安全限制",
  MINERU_PAGE_PREPARATION_FAILED: "MinerU 页面预处理失败",
  MINERU_CONSENT_MISSING: "缺少 MinerU 外发确认",
  MINERU_CANCELLED: "MinerU 任务已取消",
  PDF_INSPECTION_INCOMPLETE: "PDF 检查未完成",
  PDF_PAGE_COUNT_MISMATCH: "PDF 页数不一致",
  PDF_PAGE_EXPANSION_INCOMPLETE: "PDF 拆页未完成",
  PDF_PAGE_SET_INCOMPLETE: "PDF 页面不完整",
  REPORT_PAGE_SEQUENCE_INVALID: "报告页序异常"
};

export function processingCodeLabel(code: string) {
  return processingCodeLabels[code] || code;
}
